# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'caclulator_Maksim_Derkach.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(662, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Calculator.sizePolicy().hasHeightForWidth())
        Calculator.setSizePolicy(sizePolicy)
        Calculator.setStyleSheet("QDialog{\n"
"    background-color: #ffffff;\n"
"\n"
"}")
        self.label_output = QtWidgets.QLabel(Calculator)
        self.label_output.setGeometry(QtCore.QRect(0, 0, 661, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_output.sizePolicy().hasHeightForWidth())
        self.label_output.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        self.label_output.setFont(font)
        self.label_output.setStyleSheet("QLabel\n"
"{\n"
" qproperty-alignment: \'AlignVCenter | AlignRight\';\n"
"color:#3399ff;\n"
"    border: 2px solid;\n"
"border-color: #ff0066;\n"
"\n"
"\n"
"}\n"
"")
        self.label_output.setObjectName("label_output")
        self.gridLayoutWidget = QtWidgets.QWidget(Calculator)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 60, 661, 341))
        self.gridLayoutWidget.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.qqq = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.qqq.setContentsMargins(0, 0, 0, 0)
        self.qqq.setSpacing(0)
        self.qqq.setObjectName("qqq")
        self.pushButton_three = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_three.sizePolicy().hasHeightForWidth())
        self.pushButton_three.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_three.setFont(font)
        self.pushButton_three.setToolTipDuration(0)
        self.pushButton_three.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_three.setObjectName("pushButton_three")
        self.qqq.addWidget(self.pushButton_three, 3, 5, 1, 1)
        self.pushButton_cos = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cos.sizePolicy().hasHeightForWidth())
        self.pushButton_cos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_cos.setFont(font)
        self.pushButton_cos.setToolTipDuration(0)
        self.pushButton_cos.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_cos.setObjectName("pushButton_cos")
        self.qqq.addWidget(self.pushButton_cos, 2, 1, 1, 1)
        self.pushButton_procent = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_procent.sizePolicy().hasHeightForWidth())
        self.pushButton_procent.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_procent.setFont(font)
        self.pushButton_procent.setToolTipDuration(0)
        self.pushButton_procent.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_procent.setObjectName("pushButton_procent")
        self.qqq.addWidget(self.pushButton_procent, 0, 5, 1, 1)
        self.pushButton_two = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_two.sizePolicy().hasHeightForWidth())
        self.pushButton_two.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_two.setFont(font)
        self.pushButton_two.setToolTipDuration(0)
        self.pushButton_two.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_two.setObjectName("pushButton_two")
        self.qqq.addWidget(self.pushButton_two, 3, 4, 1, 1)
        self.pushButton_six = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_six.sizePolicy().hasHeightForWidth())
        self.pushButton_six.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_six.setFont(font)
        self.pushButton_six.setToolTipDuration(0)
        self.pushButton_six.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_six.setObjectName("pushButton_six")
        self.qqq.addWidget(self.pushButton_six, 2, 5, 1, 1)
        self.pushButton_dot = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_dot.sizePolicy().hasHeightForWidth())
        self.pushButton_dot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_dot.setFont(font)
        self.pushButton_dot.setToolTipDuration(0)
        self.pushButton_dot.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.qqq.addWidget(self.pushButton_dot, 4, 4, 1, 1)
        self.pushButton_sin = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_sin.sizePolicy().hasHeightForWidth())
        self.pushButton_sin.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_sin.setFont(font)
        self.pushButton_sin.setToolTipDuration(0)
        self.pushButton_sin.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_sin.setObjectName("pushButton_sin")
        self.qqq.addWidget(self.pushButton_sin, 1, 1, 1, 1)
        self.pushButton_deg = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_deg.sizePolicy().hasHeightForWidth())
        self.pushButton_deg.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_deg.setFont(font)
        self.pushButton_deg.setToolTipDuration(0)
        self.pushButton_deg.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_deg.setObjectName("pushButton_deg")
        self.qqq.addWidget(self.pushButton_deg, 0, 1, 1, 1)
        self.pushButton_one = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_one.sizePolicy().hasHeightForWidth())
        self.pushButton_one.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_one.setFont(font)
        self.pushButton_one.setToolTipDuration(0)
        self.pushButton_one.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_one.setObjectName("pushButton_one")
        self.qqq.addWidget(self.pushButton_one, 3, 3, 1, 1)
        self.pushButton_nine = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_nine.sizePolicy().hasHeightForWidth())
        self.pushButton_nine.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_nine.setFont(font)
        self.pushButton_nine.setToolTipDuration(0)
        self.pushButton_nine.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_nine.setObjectName("pushButton_nine")
        self.qqq.addWidget(self.pushButton_nine, 1, 5, 1, 1)
        self.pushButton_eight = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_eight.sizePolicy().hasHeightForWidth())
        self.pushButton_eight.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_eight.setFont(font)
        self.pushButton_eight.setToolTipDuration(0)
        self.pushButton_eight.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_eight.setObjectName("pushButton_eight")
        self.qqq.addWidget(self.pushButton_eight, 1, 4, 1, 1)
        self.pushButton_multiply = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_multiply.sizePolicy().hasHeightForWidth())
        self.pushButton_multiply.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_multiply.setFont(font)
        self.pushButton_multiply.setToolTipDuration(0)
        self.pushButton_multiply.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_multiply.setObjectName("pushButton_multiply")
        self.qqq.addWidget(self.pushButton_multiply, 2, 6, 1, 1)
        self.pushButton_tan = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_tan.sizePolicy().hasHeightForWidth())
        self.pushButton_tan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_tan.setFont(font)
        self.pushButton_tan.setToolTipDuration(0)
        self.pushButton_tan.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_tan.setObjectName("pushButton_tan")
        self.qqq.addWidget(self.pushButton_tan, 3, 1, 1, 1)
        self.pushButton_power = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_power.sizePolicy().hasHeightForWidth())
        self.pushButton_power.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_power.setFont(font)
        self.pushButton_power.setToolTipDuration(0)
        self.pushButton_power.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_power.setObjectName("pushButton_power")
        self.qqq.addWidget(self.pushButton_power, 4, 2, 1, 1)
        self.pushButton_four = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_four.sizePolicy().hasHeightForWidth())
        self.pushButton_four.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_four.setFont(font)
        self.pushButton_four.setToolTipDuration(0)
        self.pushButton_four.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_four.setObjectName("pushButton_four")
        self.qqq.addWidget(self.pushButton_four, 2, 3, 1, 1)
        self.pushButton_minus = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_minus.sizePolicy().hasHeightForWidth())
        self.pushButton_minus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_minus.setFont(font)
        self.pushButton_minus.setToolTipDuration(0)
        self.pushButton_minus.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.qqq.addWidget(self.pushButton_minus, 3, 6, 1, 1)
        self.pushButton_factorial = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_factorial.sizePolicy().hasHeightForWidth())
        self.pushButton_factorial.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_factorial.setFont(font)
        self.pushButton_factorial.setToolTipDuration(0)
        self.pushButton_factorial.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_factorial.setObjectName("pushButton_factorial")
        self.qqq.addWidget(self.pushButton_factorial, 0, 2, 1, 1)
        self.pushButton_equals = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_equals.sizePolicy().hasHeightForWidth())
        self.pushButton_equals.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_equals.setFont(font)
        self.pushButton_equals.setToolTipDuration(0)
        self.pushButton_equals.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid;\n"
"    background-color: #3399ff;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #3399ff)\n"
"}R")
        self.pushButton_equals.setObjectName("pushButton_equals")
        self.qqq.addWidget(self.pushButton_equals, 4, 5, 1, 1)
        self.pushButton_seven = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_seven.sizePolicy().hasHeightForWidth())
        self.pushButton_seven.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_seven.setFont(font)
        self.pushButton_seven.setToolTipDuration(0)
        self.pushButton_seven.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_seven.setObjectName("pushButton_seven")
        self.qqq.addWidget(self.pushButton_seven, 1, 3, 1, 1)
        self.pushButton_plus = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_plus.sizePolicy().hasHeightForWidth())
        self.pushButton_plus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_plus.setFont(font)
        self.pushButton_plus.setToolTipDuration(0)
        self.pushButton_plus.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.qqq.addWidget(self.pushButton_plus, 4, 6, 1, 1)
        self.pushButton_in = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_in.sizePolicy().hasHeightForWidth())
        self.pushButton_in.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_in.setFont(font)
        self.pushButton_in.setToolTipDuration(0)
        self.pushButton_in.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_in.setObjectName("pushButton_in")
        self.qqq.addWidget(self.pushButton_in, 1, 2, 1, 1)
        self.pushButton_zero = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_zero.sizePolicy().hasHeightForWidth())
        self.pushButton_zero.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_zero.setFont(font)
        self.pushButton_zero.setToolTipDuration(0)
        self.pushButton_zero.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_zero.setObjectName("pushButton_zero")
        self.qqq.addWidget(self.pushButton_zero, 4, 3, 1, 1)
        self.pushButton_log = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_log.sizePolicy().hasHeightForWidth())
        self.pushButton_log.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_log.setFont(font)
        self.pushButton_log.setToolTipDuration(0)
        self.pushButton_log.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_log.setObjectName("pushButton_log")
        self.qqq.addWidget(self.pushButton_log, 2, 2, 1, 1)
        self.pushButton_divided = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_divided.sizePolicy().hasHeightForWidth())
        self.pushButton_divided.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_divided.setFont(font)
        self.pushButton_divided.setToolTipDuration(0)
        self.pushButton_divided.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_divided.setObjectName("pushButton_divided")
        self.qqq.addWidget(self.pushButton_divided, 1, 6, 1, 1)
        self.pushButton_rad = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_rad.sizePolicy().hasHeightForWidth())
        self.pushButton_rad.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_rad.setFont(font)
        self.pushButton_rad.setToolTipDuration(0)
        self.pushButton_rad.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_rad.setObjectName("pushButton_rad")
        self.qqq.addWidget(self.pushButton_rad, 0, 0, 1, 1)
        self.pushButton_root = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_root.sizePolicy().hasHeightForWidth())
        self.pushButton_root.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_root.setFont(font)
        self.pushButton_root.setToolTipDuration(0)
        self.pushButton_root.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_root.setObjectName("pushButton_root")
        self.qqq.addWidget(self.pushButton_root, 3, 2, 1, 1)
        self.pushButton_five = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_five.sizePolicy().hasHeightForWidth())
        self.pushButton_five.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_five.setFont(font)
        self.pushButton_five.setToolTipDuration(0)
        self.pushButton_five.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_five.setObjectName("pushButton_five")
        self.qqq.addWidget(self.pushButton_five, 2, 4, 1, 1)
        self.pushButton_clear = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_clear.sizePolicy().hasHeightForWidth())
        self.pushButton_clear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setToolTipDuration(0)
        self.pushButton_clear.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.qqq.addWidget(self.pushButton_clear, 0, 6, 1, 1)
        self.pushButton_lnv = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_lnv.sizePolicy().hasHeightForWidth())
        self.pushButton_lnv.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_lnv.setFont(font)
        self.pushButton_lnv.setToolTipDuration(0)
        self.pushButton_lnv.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_lnv.setObjectName("pushButton_lnv")
        self.qqq.addWidget(self.pushButton_lnv, 1, 0, 1, 1)
        self.pushButton_exp = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_exp.sizePolicy().hasHeightForWidth())
        self.pushButton_exp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_exp.setFont(font)
        self.pushButton_exp.setToolTipDuration(0)
        self.pushButton_exp.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_exp.setObjectName("pushButton_exp")
        self.qqq.addWidget(self.pushButton_exp, 4, 1, 1, 1)
        self.pushButton_bracket_left = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_bracket_left.sizePolicy().hasHeightForWidth())
        self.pushButton_bracket_left.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_bracket_left.setFont(font)
        self.pushButton_bracket_left.setToolTipDuration(0)
        self.pushButton_bracket_left.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_bracket_left.setObjectName("pushButton_bracket_left")
        self.qqq.addWidget(self.pushButton_bracket_left, 0, 3, 1, 1)
        self.pushButton_ans = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ans.sizePolicy().hasHeightForWidth())
        self.pushButton_ans.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_ans.setFont(font)
        self.pushButton_ans.setToolTipDuration(0)
        self.pushButton_ans.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_ans.setObjectName("pushButton_ans")
        self.qqq.addWidget(self.pushButton_ans, 4, 0, 1, 1)
        self.pushButton_bracket_right = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_bracket_right.sizePolicy().hasHeightForWidth())
        self.pushButton_bracket_right.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_bracket_right.setFont(font)
        self.pushButton_bracket_right.setToolTipDuration(0)
        self.pushButton_bracket_right.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_bracket_right.setObjectName("pushButton_bracket_right")
        self.qqq.addWidget(self.pushButton_bracket_right, 0, 4, 1, 1)
        self.pushButton_pi = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_pi.sizePolicy().hasHeightForWidth())
        self.pushButton_pi.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_pi.setFont(font)
        self.pushButton_pi.setToolTipDuration(0)
        self.pushButton_pi.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_pi.setObjectName("pushButton_pi")
        self.qqq.addWidget(self.pushButton_pi, 2, 0, 1, 1)
        self.pushButton_exp_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_exp_2.sizePolicy().hasHeightForWidth())
        self.pushButton_exp_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_exp_2.setFont(font)
        self.pushButton_exp_2.setToolTipDuration(0)
        self.pushButton_exp_2.setStyleSheet("QPushButton\n"
"{\n"
"    border: 1px solid;\n"
"border-color: #ff0066;\n"
"\n"
"    color:#0000cc;\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
" stop:0 #ffffff, stop:1 #6666ff)\n"
"}R")
        self.pushButton_exp_2.setObjectName("pushButton_exp_2")
        self.qqq.addWidget(self.pushButton_exp_2, 3, 0, 1, 1)

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Dialog"))
        self.label_output.setText(_translate("Calculator", "0"))
        self.pushButton_three.setText(_translate("Calculator", "3"))
        self.pushButton_cos.setText(_translate("Calculator", "cos"))
        self.pushButton_procent.setText(_translate("Calculator", "%"))
        self.pushButton_two.setText(_translate("Calculator", "2"))
        self.pushButton_six.setText(_translate("Calculator", "6"))
        self.pushButton_dot.setText(_translate("Calculator", "."))
        self.pushButton_sin.setText(_translate("Calculator", "sin"))
        self.pushButton_deg.setText(_translate("Calculator", "deg"))
        self.pushButton_one.setText(_translate("Calculator", "1"))
        self.pushButton_nine.setText(_translate("Calculator", "9"))
        self.pushButton_eight.setText(_translate("Calculator", "8"))
        self.pushButton_multiply.setText(_translate("Calculator", "X"))
        self.pushButton_tan.setText(_translate("Calculator", "tan"))
        self.pushButton_power.setText(_translate("Calculator", "x²"))
        self.pushButton_four.setText(_translate("Calculator", "4"))
        self.pushButton_minus.setText(_translate("Calculator", "-"))
        self.pushButton_factorial.setText(_translate("Calculator", "x!"))
        self.pushButton_equals.setText(_translate("Calculator", "="))
        self.pushButton_seven.setText(_translate("Calculator", "7"))
        self.pushButton_plus.setText(_translate("Calculator", "+"))
        self.pushButton_in.setText(_translate("Calculator", "ln"))
        self.pushButton_zero.setText(_translate("Calculator", "0"))
        self.pushButton_log.setText(_translate("Calculator", "log"))
        self.pushButton_divided.setText(_translate("Calculator", "/"))
        self.pushButton_rad.setText(_translate("Calculator", "rad"))
        self.pushButton_root.setText(_translate("Calculator", "√"))
        self.pushButton_five.setText(_translate("Calculator", "5"))
        self.pushButton_clear.setText(_translate("Calculator", "AC"))
        self.pushButton_lnv.setText(_translate("Calculator", "Inv"))
        self.pushButton_exp.setText(_translate("Calculator", "EXP"))
        self.pushButton_bracket_left.setText(_translate("Calculator", "("))
        self.pushButton_ans.setText(_translate("Calculator", "Ans"))
        self.pushButton_bracket_right.setText(_translate("Calculator", ")"))
        self.pushButton_pi.setText(_translate("Calculator", "π"))
        self.pushButton_exp_2.setText(_translate("Calculator", "e"))



