capitals = {
    'Kyiv': 'Ukraine',
    'Paris': 'France',
    'Berlin': 'Germany',
    'London': 'United Kingdom',
    'Rome': 'Italy',
    'Tokyo': 'Japan',
    'Beijing': 'China',
    'Ottawa': 'Canada',
    'Washington': 'USA',
    'Cairo': 'Egypt',
    'Canberra': 'Australia',
    'Stockholm': 'Sweden',
    'Brasília': 'Brazil',
    'Ankara': 'Turkey',
    'New Delhi': 'India',
    'Dublin': 'Ireland',
    'Mexico City': 'Mexico',
    'Oslo': 'Norway',
    'Johannesburg': 'South Africa',
    # Додайте більше столиць та країн за потребою
}